/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as FinancialRouteImport } from './routes/financial'
import { Route as DemographicsRouteImport } from './routes/demographics'
import { Route as ClinicalRouteImport } from './routes/clinical'
import { Route as IndexRouteImport } from './routes/index'

const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialRoute = FinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const DemographicsRoute = DemographicsRouteImport.update({
  id: '/demographics',
  path: '/demographics',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRoute = ClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinical': typeof ClinicalRoute
  '/demographics': typeof DemographicsRoute
  '/financial': typeof FinancialRoute
  '/operations': typeof OperationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinical': typeof ClinicalRoute
  '/demographics': typeof DemographicsRoute
  '/financial': typeof FinancialRoute
  '/operations': typeof OperationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinical': typeof ClinicalRoute
  '/demographics': typeof DemographicsRoute
  '/financial': typeof FinancialRoute
  '/operations': typeof OperationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clinical' | '/demographics' | '/financial' | '/operations'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clinical' | '/demographics' | '/financial' | '/operations'
  id:
    | '__root__'
    | '/'
    | '/clinical'
    | '/demographics'
    | '/financial'
    | '/operations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicalRoute: typeof ClinicalRoute
  DemographicsRoute: typeof DemographicsRoute
  FinancialRoute: typeof FinancialRoute
  OperationsRoute: typeof OperationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial': {
      id: '/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof FinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demographics': {
      id: '/demographics'
      path: '/demographics'
      fullPath: '/demographics'
      preLoaderRoute: typeof DemographicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical': {
      id: '/clinical'
      path: '/clinical'
      fullPath: '/clinical'
      preLoaderRoute: typeof ClinicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicalRoute: ClinicalRoute,
  DemographicsRoute: DemographicsRoute,
  FinancialRoute: FinancialRoute,
  OperationsRoute: OperationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
